'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ExternalLink, CheckCircle, Tag, AlertTriangle, ChevronDown } from 'lucide-react';
import { Button } from '@/components/ui';

interface Threat {
    id: string;
    name: string;
    category: string;
    source: string;
    severity: string;
    affectedComponent: string;
    description: string;
    dread: {
        damage: number;
        reproducibility: number;
        exploitability: number;
        affectedUsers: number;
        discoverability: number;
        total: number;
    };
    mitigation: string;
    status: string;
}

interface JiraExportModalProps {
    threat: Threat;
    componentName: string;
    onClose: () => void;
    onSuccess: (ticketId: string) => void;
}

export function JiraExportModal({ threat, componentName, onClose, onSuccess }: JiraExportModalProps) {
    const [isCreating, setIsCreating] = useState(false);
    const [project, setProject] = useState('SECURITY');
    const [issueType, setIssueType] = useState('Bug');

    const getPriorityFromSeverity = (severity: string) => {
        switch (severity) {
            case 'critical': return 'Highest';
            case 'high': return 'High';
            case 'medium': return 'Medium';
            case 'low': return 'Low';
            default: return 'Medium';
        }
    };

    const ticketTitle = `[Security] ${threat.severity.charAt(0).toUpperCase() + threat.severity.slice(1)}: ${threat.name} in ${componentName}`;

    const ticketDescription = `
## Threat Summary
${threat.description}

## Affected Component
- **Component:** ${componentName}
- **Category:** ${threat.category}
- **Source:** ${threat.source}

## DREAD Score
| Metric | Score |
|--------|-------|
| Damage | ${threat.dread.damage}/10 |
| Reproducibility | ${threat.dread.reproducibility}/10 |
| Exploitability | ${threat.dread.exploitability}/10 |
| Affected Users | ${threat.dread.affectedUsers}/10 |
| Discoverability | ${threat.dread.discoverability}/10 |
| **Total** | **${threat.dread.total}/50** |

## Recommended Mitigation
${threat.mitigation}

---
_Generated by Virantis Threat Modeling Platform_
  `.trim();

    const labels = ['security', 'threat-model', 'agentic-ai'];

    const handleCreateTicket = async () => {
        setIsCreating(true);

        // Simulate API call
        await new Promise((resolve) => setTimeout(resolve, 1500));

        // Generate mock ticket ID
        const ticketId = `${project}-${Math.floor(1000 + Math.random() * 9000)}`;

        setIsCreating(false);
        onSuccess(ticketId);
    };

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="modal-overlay"
                onClick={onClose}
            >
                <motion.div
                    initial={{ opacity: 0, scale: 0.95, y: 20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95, y: 20 }}
                    transition={{ duration: 0.2 }}
                    className="modal-content max-w-2xl"
                    onClick={(e) => e.stopPropagation()}
                >
                    {/* Header */}
                    <div className="flex items-center justify-between mb-6">
                        <div className="flex items-center gap-3">
                            <div className="p-2 rounded-lg bg-electric-blue/10">
                                <ExternalLink className="w-5 h-5 text-electric-blue" />
                            </div>
                            <h2 className="text-xl font-semibold text-white">Create Jira Ticket</h2>
                        </div>
                        <button
                            onClick={onClose}
                            className="p-2 hover:bg-white/5 rounded-lg transition-colors"
                        >
                            <X className="w-5 h-5 text-zinc-400" />
                        </button>
                    </div>

                    {/* Ticket Preview */}
                    <div className="space-y-6">
                        {/* Project & Type Selectors */}
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm text-zinc-400 mb-2">Project</label>
                                <div className="relative">
                                    <select
                                        value={project}
                                        onChange={(e) => setProject(e.target.value)}
                                        className="w-full appearance-none bg-midnight border border-zinc-800 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan pr-10"
                                    >
                                        <option value="SECURITY">SECURITY</option>
                                        <option value="APPSEC">APPSEC</option>
                                        <option value="INFOSEC">INFOSEC</option>
                                    </select>
                                    <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-500 pointer-events-none" />
                                </div>
                            </div>
                            <div>
                                <label className="block text-sm text-zinc-400 mb-2">Issue Type</label>
                                <div className="relative">
                                    <select
                                        value={issueType}
                                        onChange={(e) => setIssueType(e.target.value)}
                                        className="w-full appearance-none bg-midnight border border-zinc-800 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan pr-10"
                                    >
                                        <option value="Bug">Bug</option>
                                        <option value="Task">Task</option>
                                        <option value="Story">Story</option>
                                    </select>
                                    <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-500 pointer-events-none" />
                                </div>
                            </div>
                        </div>

                        {/* Priority */}
                        <div>
                            <label className="block text-sm text-zinc-400 mb-2">Priority</label>
                            <div className="flex items-center gap-2 px-4 py-3 bg-midnight border border-zinc-800 rounded-lg">
                                <AlertTriangle className={`w-4 h-4 ${threat.severity === 'critical' ? 'text-red-500' :
                                        threat.severity === 'high' ? 'text-orange-500' :
                                            threat.severity === 'medium' ? 'text-yellow-500' : 'text-green-500'
                                    }`} />
                                <span className="text-white">{getPriorityFromSeverity(threat.severity)}</span>
                            </div>
                        </div>

                        {/* Title */}
                        <div>
                            <label className="block text-sm text-zinc-400 mb-2">Title</label>
                            <div className="px-4 py-3 bg-midnight border border-zinc-800 rounded-lg">
                                <p className="text-white text-sm">{ticketTitle}</p>
                            </div>
                        </div>

                        {/* Description Preview */}
                        <div>
                            <label className="block text-sm text-zinc-400 mb-2">Description</label>
                            <div className="px-4 py-4 bg-midnight border border-zinc-800 rounded-lg max-h-48 overflow-y-auto">
                                <pre className="text-zinc-400 text-sm whitespace-pre-wrap font-sans leading-relaxed">
                                    {ticketDescription}
                                </pre>
                            </div>
                        </div>

                        {/* Labels */}
                        <div>
                            <label className="block text-sm text-zinc-400 mb-2">Labels</label>
                            <div className="flex flex-wrap gap-2">
                                {labels.map((label) => (
                                    <span key={label} className="inline-flex items-center gap-1 px-3 py-1 rounded-full bg-purple/10 text-purple text-sm">
                                        <Tag className="w-3 h-3" />
                                        {label}
                                    </span>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Actions */}
                    <div className="flex items-center justify-end gap-3 mt-8 pt-6 border-t border-zinc-800">
                        <Button variant="secondary" onClick={onClose}>
                            Cancel
                        </Button>
                        <Button
                            variant="primary"
                            loading={isCreating}
                            icon={!isCreating ? <CheckCircle className="w-4 h-4" /> : undefined}
                            onClick={handleCreateTicket}
                        >
                            {isCreating ? 'Creating...' : 'Create Ticket'}
                        </Button>
                    </div>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
}
